= Sim Ming Hui Melodies (Happytreat) - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images/Happytreat.png
:stylesDir: ../stylesheets

== PROJECT: NUS Hangs

---

== Overview
NUS Hangs is a desktop Schedule Manager application. It has a GUI but most of the user interactions happen using a CLI (Command Line Interface). It is a Java application written by developers of F11-4, to target small/mid-size interest/sttudy groups in NUS.

== Summary of contributions

* *Major enhancement*: Created a group class and added corresponding group functions:
i.e. add_group, delete_group, edit_group, register, delete_member, find_group, view_group.
** What it does: The group class allows users to categorise persons into groups and facilitate free time slot allocation.
*** add_group: Add a new group which will appear in the right group panel of UI.
*** delete_group: Delete an existing group and remove all current members from that group.
*** edit_group: Edit an existing group's name/description.
*** register: Register an existing person as a member of the group.
*** delete_member: Delete an existing member of the group.
*** find_group: Find a group based on its name.
*** view_group: View all members of the group in UI.

** Justification: This feature improves the product's functionality significantly because a user can now better organise his contacts into groups and easily coordinate common time slots to meet.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands:
*** The integration of Group and Person Class. For instance, delete_group requires the group to be deleted and all reference to the group in all Persons registered to be deleted. Edit_group also requires the group to be edited and all reference to the group (reference by the person who is a member) to be edited correspondingly.
*** Changes in the UI and Storage components. For instance, the GroupPanel has to be created to show and update all groups. Group Data have to stored after the app closes inside addressbook.xml and reloaded into the app as Group obects once the user reopens the app.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: Enhance `list` command to list both groups and persons. Added a `list INDEX` command to show all the groups that the person at INDEX is currently in.

* *Minor enhancement*: Created short hands/short forms for most commands.

* *Minor enhancement*: Refactored UniquePersonList into UniqueList<T> for different classes: Groups, Person and Timetable. 

* *Minor enhancement*: Created an Abstract class Entity which Group and Person extends from to allow for polymorphism: Refactored the ModelManager and AddressBook function to include Polymorphism. E.g. addPerson() --> add() which performs add on Group or Person class based on polymorphism.

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=happytreat[Functional and Test code]]  _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.3` (3 releases) on GitHub
** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage by 5% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Edit the Model Sequence Diagram in Dev Guide to include Group and Entity classes: https://github.com[#14]
*** Edit the UI Sequence Diagram in Dev Guide to include Group UI features.
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Reported bugs and suggestions for another team (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the group feature I added was adopted by several other teammates (https://github.com[1], https://github.com[2])
*** Create a CommandUtil.java with many common functiosn reused by different commands including those in AB4 and those used by other teammates.) Several other teammates reused the functions I have created in CommandUtil. ()


_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]

---

_{Optionally, you may include other projects in your portfolio.}_
