= Ng Yuan Yun Nigel (nigelngyy) - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NUS Hangs

---

== Overview
NUS Hangs is a desktop Schedule Manager application. It has a GUI but most of the user interactions happen using a CLI (Command Line Interface). It is a Java application written by developers of F11-4, to target small/mid-size interest/sttudy groups in NUS.k application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to find the time slots at which the members of a group are available at*
** What it does: allows the user to easily find a suitable timing for a gathering or meeting with his or her group members in two intuitive methods.
*** view_slots_all : finds all of the time slots at which every person in a group is available at.
*** view_slots_ranked : ranks all of the time slots in terms of the number of people available, with a minimum required number of people.

** Justification: This feature improves the product significantly because finding a suitable timing to organise meetings is the key aspect of the application.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of efficient algorithms. The implementation too was challenging as it required a comprehensive understanding of the implementation of both the timetable and group feature and integration between the two.

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=nigelngyy[Functional and Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (3 releases) on GitHub
** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage from % to % (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
